create database workforce4;
use workforce4;

CREATE TABLE employees (
    employee_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    team VARCHAR(100) NOT NULL,
    role VARCHAR(50),
    level VARCHAR(30),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO employees (name, team, role, level) VALUES
('Aarav Sharma','Team_1','Backend','Junior'),
('Vivaan Mehta','Team_1','Frontend','Mid'),
('Aditya Verma','Team_1','QA','Senior'),
('Arjun Patel','Team_1','Backend','Staff'),
('Rohan Gupta','Team_1','Frontend','Junior'),

('Ananya Iyer','Team_2','Backend','Mid'),
('Diya Nair','Team_2','QA','Senior'),
('Kavya Rao','Team_2','Frontend','Staff'),
('Pooja Singh','Team_2','Backend','Junior'),
('Sneha Kulkarni','Team_2','QA','Mid'),

('Rahul Malhotra','Team_3','Backend','Senior'),
('Kunal Khanna','Team_3','Frontend','Staff'),
('Siddharth Jain','Team_3','QA','Junior'),
('Amit Agarwal','Team_3','Backend','Mid'),
('Nikhil Bansal','Team_3','Frontend','Senior'),

('Priya Choudhary','Team_4','QA','Staff'),
('Neha Saxena','Team_4','Backend','Junior'),
('Ritu Mishra','Team_4','Frontend','Mid'),
('Shreya Ghosh','Team_4','QA','Senior'),
('Isha Banerjee','Team_4','Backend','Staff'),

('Mohit Arora','Team_5','Frontend','Junior'),
('Varun Kapoor','Team_5','QA','Mid'),
('Manish Tiwari','Team_5','Backend','Senior'),
('Deepak Yadav','Team_5','Frontend','Staff'),
('Sachin Pandey','Team_5','QA','Junior'),

('Abhishek Singh','Team_6','Backend','Mid'),
('Saurabh Mishra','Team_6','Frontend','Senior'),
('Ravi Prakash','Team_6','QA','Staff'),
('Vikas Reddy','Team_6','Backend','Junior'),
('Karthik Subramanian','Team_6','Frontend','Mid'),

('Pranav Kulkarni','Team_7','QA','Senior'),
('Omkar Joshi','Team_7','Backend','Staff'),
('Akash Deshpande','Team_7','Frontend','Junior'),
('Swapnil Patil','Team_7','QA','Mid'),
('Tejas Kulkarni','Team_7','Backend','Senior'),

('Ankit Srivastava','Team_8','Frontend','Staff'),
('Harsh Vardhan','Team_8','QA','Junior'),
('Rakesh Kumar','Team_8','Backend','Mid'),
('Sunil Rawat','Team_8','Frontend','Senior'),
('Alok Saxena','Team_8','QA','Staff'),

('Rajesh Menon','Team_9','Backend','Junior'),
('Suresh Pillai','Team_9','Frontend','Mid'),
('Naveen Kumar','Team_9','QA','Senior'),
('Vijay Krishnan','Team_9','Backend','Staff'),
('Arvind Iyer','Team_9','Frontend','Junior'),

('Gokul Raj','Team_10','QA','Mid'),
('Pradeep N','Team_10','Backend','Senior'),
('Balaji S','Team_10','Frontend','Staff'),
('Senthil Kumar','Team_10','QA','Junior'),
('Madhan R','Team_10','Backend','Mid'),

('Rohit Shetty','Team_1','Frontend','Senior'),
('Kiran Hegde','Team_1','QA','Staff'),
('Umesh Naik','Team_1','Backend','Junior'),
('Nitin Pawar','Team_1','Frontend','Mid'),
('Ajay Kulkarni','Team_1','QA','Senior'),

('Shalini Verma','Team_2','Backend','Staff'),
('Pallavi Joshi','Team_2','Frontend','Junior'),
('Monica Arora','Team_2','QA','Mid'),
('Rekha Malhotra','Team_2','Backend','Senior'),
('Sonali Bhat','Team_2','Frontend','Staff'),

('Tarun Chopra','Team_3','QA','Junior'),
('Yash Aggarwal','Team_3','Backend','Mid'),
('Ritvik Khurana','Team_3','Frontend','Senior'),
('Apoorva Saxena','Team_3','QA','Staff'),
('Ishaan Sethi','Team_3','Backend','Junior'),

('Mehul Shah','Team_4','Frontend','Mid'),
('Jayesh Patel','Team_4','QA','Senior'),
('Nilesh Desai','Team_4','Backend','Staff'),
('Parth Shah','Team_4','Frontend','Junior'),
('Hemant Joshi','Team_4','QA','Mid'),

('Aishwarya Kulkarni','Team_5','Backend','Senior'),
('Smita Patil','Team_5','Frontend','Staff'),
('Rupali Deshmukh','Team_5','QA','Junior'),
('Prajakta Joshi','Team_5','Backend','Mid'),
('Mrunal Kulkarni','Team_5','Frontend','Senior'),

('Sanjay Rao','Team_6','Backend','Junior'),
('Karthika Menon','Team_6','Frontend','Mid'),
('Ashwin Nair','Team_6','QA','Senior'),
('Meera Pillai','Team_6','Backend','Staff'),
('Anil Kumar','Team_6','Frontend','Junior'),

('Divya Prasad','Team_7','Backend','Mid'),
('Ramesh Iyer','Team_7','QA','Senior'),
('Lakshmi Narayanan','Team_7','Frontend','Staff'),
('Prakash Rao','Team_7','Backend','Junior'),
('Swetha R','Team_7','QA','Mid'),

('Vivek Anand','Team_8','Backend','Senior'),
('Sonal Gupta','Team_8','Frontend','Staff'),
('Manoj Sinha','Team_8','QA','Junior'),
('Pankaj Verma','Team_8','Backend','Mid'),
('Ritu Sharma','Team_8','Frontend','Senior'),

('Abhay Kulkarni','Team_9','QA','Staff'),
('Nandini Joshi','Team_9','Backend','Junior'),
('Keshav Malhotra','Team_9','Frontend','Mid'),
('Tanya Arora','Team_9','QA','Senior'),
('Rohini Deshpande','Team_9','Backend','Staff'),

('Shubham Mishra','Team_10','Frontend','Junior'),
('Kunal Arvind','Team_10','QA','Mid'),
('Sandeep Reddy','Team_10','Backend','Senior'),
('Gaurav Saxena','Team_10','Frontend','Staff'),
('Nikhita Rao','Team_10','QA','Junior'),

('Suresh Naidu','Team_1','Backend','Mid'),
('Anjana Krishnan','Team_1','Frontend','Senior'),
('Haritha M','Team_1','QA','Staff'),
('Arun Balaji','Team_1','Backend','Junior'),
('Lokesh Patil','Team_1','Frontend','Mid'),

('Chirag Shah','Team_2','QA','Senior'),
('Bhavya Jain','Team_2','Backend','Staff'),
('Naveena R','Team_2','Frontend','Junior'),
('Rajat Goel','Team_2','QA','Mid'),
('Kishore K','Team_2','Backend','Senior'),

('Apoorv Mishra','Team_3','Frontend','Staff'),
('Rina Sen','Team_3','QA','Junior'),
('Anup Das','Team_3','Backend','Mid'),
('Soumya Ghosh','Team_3','Frontend','Senior'),
('Debashish Paul','Team_3','QA','Staff'),

('Mahesh K','Team_4','Backend','Junior'),
('Jyoti Malhotra','Team_4','Frontend','Mid'),
('Shantanu Bose','Team_4','QA','Senior'),
('Kalyani Iyer','Team_4','Backend','Staff'),
('Rohit Bansal','Team_4','Frontend','Junior'),

('Sameer Khan','Team_5','QA','Mid'),
('Faisal Ahmed','Team_5','Backend','Senior'),
('Aditi Kapoor','Team_5','Frontend','Staff'),
('Neelam Yadav','Team_5','QA','Junior'),
('Rahul Tripathi','Team_5','Backend','Mid'),

('Prakash S','Team_6','Frontend','Senior'),
('Manisha Kulkarni','Team_6','QA','Staff'),
('Dinesh R','Team_6','Backend','Junior'),
('Pavitra Joshi','Team_6','Frontend','Mid'),
('Kiran Shetty','Team_6','QA','Senior'),

('Uday Chandra','Team_7','Backend','Staff'),
('Aishwarya N','Team_7','Frontend','Junior'),
('Sumanth Rao','Team_7','QA','Mid'),
('Tanvi Kulkarni','Team_7','Backend','Senior'),
('Naveed Hussain','Team_7','Frontend','Staff'),

('Harpreet Singh','Team_8','QA','Junior'),
('Simran Kaur','Team_8','Backend','Mid'),
('Girish Hegde','Team_8','Frontend','Senior'),
('Padma Lakshmi','Team_8','QA','Staff'),
('Arjun Nayak','Team_8','Backend','Junior'),

('Vimal Raj','Team_9','Frontend','Mid'),
('Sathish Kumar','Team_9','QA','Senior'),
('Reema Thomas','Team_9','Backend','Staff'),
('Ajith Menon','Team_9','Frontend','Junior'),
('Sowmya Reddy','Team_9','QA','Mid'),

('Raghav Goenka','Team_10','Backend','Senior'),
('Nisha Agarwal','Team_10','Frontend','Staff'),
('Akshay Kulkarni','Team_10','QA','Junior'),
('Varsha Joshi','Team_10','Backend','Mid'),
('Prateek Mathur','Team_10','Frontend','Senior'),

('Ravindra Kulkarni','Team_1','Backend','Junior'),
('Sahil Chawla','Team_1','Frontend','Mid'),
('Nitin Goswami','Team_1','QA','Senior'),
('Puneet Arora','Team_1','Backend','Staff'),
('Ashutosh Dubey','Team_1','Frontend','Junior'),

('Bharti Sinha','Team_2','Backend','Mid'),
('Kritika Malviya','Team_2','QA','Senior'),
('Rohini Kulkarni','Team_2','Frontend','Staff'),
('Ankur Saxena','Team_2','Backend','Junior'),
('Suman Verma','Team_2','QA','Mid'),

('Rajat Srivastava','Team_3','Backend','Senior'),
('Irfan Shaikh','Team_3','Frontend','Staff'),
('Naveed Khan','Team_3','QA','Junior'),
('Piyush Shukla','Team_3','Backend','Mid'),
('Abhinav Tripathi','Team_3','Frontend','Senior'),

('Kavita Joshi','Team_4','QA','Staff'),
('Sandeep Chauhan','Team_4','Backend','Junior'),
('Ruchi Agarwal','Team_4','Frontend','Mid'),
('Payal Gupta','Team_4','QA','Senior'),
('Gaurav Bhatt','Team_4','Backend','Staff'),

('Shivam Pandey','Team_5','Frontend','Junior'),
('Anmol Kaur','Team_5','QA','Mid'),
('Satyam Mishra','Team_5','Backend','Senior'),
('Rishabh Jain','Team_5','Frontend','Staff'),
('Neeraj Yadav','Team_5','QA','Junior'),

('Animesh Roy','Team_6','Backend','Mid'),
('Tushar Jain','Team_6','Frontend','Senior'),
('Rohit Negi','Team_6','QA','Staff'),
('Nikhil Tomar','Team_6','Backend','Junior'),
('Mayank Saxena','Team_6','Frontend','Mid'),

('Amanpreet Singh','Team_7','QA','Senior'),
('Guneet Kaur','Team_7','Backend','Staff'),
('Ravikant Mishra','Team_7','Frontend','Junior'),
('Saurav Paul','Team_7','QA','Mid'),
('Vishal Tandon','Team_7','Backend','Senior'),

('Monika Bhatia','Team_8','Frontend','Staff'),
('Ashish Rawat','Team_8','QA','Junior'),
('Lalit Sharma','Team_8','Backend','Mid'),
('Suresh Choudhary','Team_8','Frontend','Senior'),
('Prerna Mathur','Team_8','QA','Staff'),

('Keshav Arora','Team_9','Backend','Junior'),
('Manpreet Kaur','Team_9','Frontend','Mid'),
('Farhan Ali','Team_9','QA','Senior'),
('Nilesh Pawar','Team_9','Backend','Staff'),
('Harshit Bansal','Team_9','Frontend','Junior'),

('Ritu Kapoor','Team_10','QA','Mid'),
('Akash Goyal','Team_10','Backend','Senior'),
('Sonal Mehra','Team_10','Frontend','Staff'),
('Jatin Sehgal','Team_10','QA','Junior'),
('Mohak Mittal','Team_10','Backend','Mid'),

('Vinay Pathak','Team_1','Frontend','Senior'),
('Meenakshi Rana','Team_1','QA','Staff'),
('Deepanshu Gupta','Team_1','Backend','Junior'),
('Ishita Malhotra','Team_1','Frontend','Mid'),
('Rohit Ahuja','Team_1','QA','Senior'),

('Shubhangi Deshpande','Team_2','Backend','Staff'),
('Sanjana Kulkarni','Team_2','Frontend','Junior'),
('Tanmay Joshi','Team_2','QA','Mid'),
('Niraj Kulshreshtha','Team_2','Backend','Senior'),
('Aakash Tyagi','Team_2','Frontend','Staff'),

('Soham Ghosh','Team_3','QA','Junior'),
('Riya Chatterjee','Team_3','Backend','Mid'),
('Sayan Mukherjee','Team_3','Frontend','Senior'),
('Indranil Das','Team_3','QA','Staff'),
('Aniket Dutta','Team_3','Backend','Junior'),

('Amit Kulshrestha','Team_1','Backend','Junior'),
('Rashmi Tiwari','Team_1','Frontend','Mid'),
('Saurabh Tyagi','Team_1','QA','Senior'),
('Naveen Chandra','Team_1','Backend','Staff'),
('Ishaan Arora','Team_1','Frontend','Junior'),

('Pallav Mishra','Team_2','Backend','Mid'),
('Nidhi Bhatnagar','Team_2','QA','Senior'),
('Shivani Khanna','Team_2','Frontend','Staff'),
('Ritesh Saini','Team_2','Backend','Junior'),
('Preeti Tomar','Team_2','QA','Mid'),

('Gaurav Kulkarni','Team_3','Backend','Senior'),
('Ayesha Siddiqui','Team_3','Frontend','Staff'),
('Sanket Joshi','Team_3','QA','Junior'),
('Rahul Kuldeep','Team_3','Backend','Mid'),
('Kiran Malviya','Team_3','Frontend','Senior'),

('Monojit Sen','Team_4','QA','Staff'),
('Anupam Roy','Team_4','Backend','Junior'),
('Snehal Patwardhan','Team_4','Frontend','Mid'),
('Debanjan Das','Team_4','QA','Senior'),
('Prashant Mule','Team_4','Backend','Staff'),

('Utkarsh Singh','Team_5','Frontend','Junior'),
('Nupur Jain','Team_5','QA','Mid'),
('Vineet Awasthi','Team_5','Backend','Senior'),
('Rupal Shah','Team_5','Frontend','Staff'),
('Amitabh Verma','Team_5','QA','Junior'),

('Srinivas Rao','Team_6','Backend','Mid'),
('Keerthana S','Team_6','Frontend','Senior'),
('Shashank Pathak','Team_6','QA','Staff'),
('Rohail Khan','Team_6','Backend','Junior'),
('Abhinay Reddy','Team_6','Frontend','Mid'),

('Manoj Patil','Team_7','QA','Senior'),
('Renu Deshpande','Team_7','Backend','Staff'),
('Akilesh Kumar','Team_7','Frontend','Junior'),
('Pratik Gawande','Team_7','QA','Mid'),
('Siddhesh Naik','Team_7','Backend','Senior'),

('Anuradha Pillai','Team_8','Frontend','Staff'),
('Chetan Rawal','Team_8','QA','Junior'),
('Kishan Solanki','Team_8','Backend','Mid'),
('Vikas Chaturvedi','Team_8','Frontend','Senior'),
('Mitali Ghosh','Team_8','QA','Staff'),

('Shreyas Joshi','Team_9','Backend','Junior'),
('Farida Begum','Team_9','Frontend','Mid'),
('Abdul Rahman','Team_9','QA','Senior'),
('Dattatray More','Team_9','Backend','Staff'),
('Anmol Gupta','Team_9','Frontend','Junior'),

('Poonam Saxena','Team_10','QA','Mid'),
('Sandeep Kulshreshtha','Team_10','Backend','Senior'),
('Neha Puri','Team_10','Frontend','Staff'),
('Kartik Bansal','Team_10','QA','Junior'),
('Lakshay Mehta','Team_10','Backend','Mid'),

('Rohan Choksi','Team_1','Frontend','Senior'),
('Mehul Trivedi','Team_1','QA','Staff'),
('Deepak Kori','Team_1','Backend','Junior'),
('Aditi Singhal','Team_1','Frontend','Mid'),
('Praveen Nair','Team_1','QA','Senior'),

('Smriti Bhardwaj','Team_2','Backend','Staff'),
('Yogesh Jadhav','Team_2','Frontend','Junior'),
('Naman Goyal','Team_2','QA','Mid'),
('Ashok Rathore','Team_2','Backend','Senior'),
('Sonal Arvind','Team_2','Frontend','Staff'),

('Arnab Mukherjee','Team_3','QA','Junior'),
('Ritika Basu','Team_3','Backend','Mid'),
('Souvik Dey','Team_3','Frontend','Senior'),
('Pritam Paul','Team_3','QA','Staff'),
('Anshul Bhat','Team_3','Backend','Junior'),

('Meghana Rao','Team_4','Frontend','Mid'),
('Siddhant Kulkarni','Team_4','QA','Senior'),
('Varsha Nambiar','Team_4','Backend','Staff'),
('Ritesh Kulshreshtha','Team_4','Frontend','Junior'),

('Kunal Shekhar','Team_5','Backend','Mid'),
('Anushka Mishra','Team_5','QA','Senior'),
('Harini S','Team_5','Frontend','Staff'),
('Raghunath Iyer','Team_5','Backend','Junior'),
('Pallavi Desai','Team_5','QA','Mid'),

('Shyam Prasad','Team_6','Backend','Senior'),
('Tanisha Gupta','Team_6','Frontend','Staff'),
('Rohil Batra','Team_6','QA','Junior'),
('Naveed Ali','Team_6','Backend','Mid'),
('Charan Teja','Team_6','Frontend','Senior'),

('Sonal Bhosale','Team_7','QA','Staff'),
('Akhil Menon','Team_7','Backend','Junior'),
('Prachi Kulkarni','Team_7','Frontend','Mid'),
('Nikhil Sood','Team_7','QA','Senior'),
('Girish Kulkarni','Team_7','Backend','Staff'),

('Shivendra Pratap','Team_8','Frontend','Junior'),
('Ritika Nanda','Team_8','QA','Mid'),
('Ashwin Kumar','Team_8','Backend','Senior'),
('Poonam Chaturvedi','Team_8','Frontend','Staff'),
('Manoj D','Team_8','QA','Junior'),

('Ujjwal Saxena','Team_9','Backend','Mid'),
('Nisha Thakur','Team_9','Frontend','Senior'),
('Imran Qureshi','Team_9','QA','Staff'),
('Vivek N','Team_9','Backend','Junior'),
('Kajal Aggarwal','Team_9','Frontend','Mid'),

('Rameshwar Patil','Team_10','QA','Senior'),
('Shruti Kulshrestha','Team_10','Backend','Staff'),
('Aniket Verma','Team_10','Frontend','Junior'),
('Pawan Chauhan','Team_10','QA','Mid'),
('Saurav Mahajan','Team_10','Backend','Senior'),

('Pratiksha More','Team_1','Frontend','Staff'),
('Ashok Meena','Team_1','QA','Junior'),
('Riya Malhotra','Team_1','Backend','Mid'),
('Devansh Jain','Team_1','Frontend','Senior'),
('Arunachalam S','Team_1','QA','Staff'),

('Snehal Jadhav','Team_2','Backend','Junior'),
('Yashasvi Pandey','Team_2','Frontend','Mid'),
('Mohammad Saif','Team_2','QA','Senior'),
('Ketan Shah','Team_2','Backend','Staff'),
('Ira Sengupta','Team_2','Frontend','Junior'),

('Subodh Kulkarni','Team_3','QA','Mid'),
('Rohit Saxena','Team_3','Backend','Senior'),
('Ananya Mukherjee','Team_3','Frontend','Staff'),
('Taranjeet Singh','Team_3','QA','Junior'),
('Abhishek R','Team_3','Backend','Mid'),

('Dilip Chavan','Team_4','Frontend','Senior'),
('Sushmita Paul','Team_4','QA','Staff'),
('Ranjit Das','Team_4','Backend','Junior'),
('Khyati Mehra','Team_4','Frontend','Mid'),
('Nitin Solanki','Team_4','QA','Senior'),

('Bhaskar Rao','Team_5','Backend','Staff'),
('Madhavi K','Team_5','Frontend','Junior'),
('Arpit Mishra','Team_5','QA','Mid'),
('Shreya Malhotra','Team_5','Backend','Senior'),
('Jaspreet Kaur','Team_5','Frontend','Staff'),

('Vishnu Prasad','Team_6','QA','Junior'),
('Sonalika Dey','Team_6','Backend','Mid'),
('Rajat Kulshrestha','Team_6','Frontend','Senior'),
('Apoorva Naik','Team_6','QA','Staff'),
('Hari Krishnan','Team_6','Backend','Junior'),

('Ravikumar S','Team_7','Backend','Junior'),
('Anjali Shetty','Team_7','Frontend','Mid'),
('Koushik Dutta','Team_7','QA','Senior'),
('Mehul Jain','Team_7','Backend','Staff'),
('Shraddha Joshi','Team_7','Frontend','Junior'),

('Sumanth Hegde','Team_8','Backend','Mid'),
('Pavithra R','Team_8','QA','Senior'),
('Apoorv Mehta','Team_8','Frontend','Staff'),
('Naveen Raju','Team_8','Backend','Junior'),
('Kiranmayi S','Team_8','QA','Mid'),

('Anirudh Sharma','Team_9','Backend','Senior'),
('Palak Bansal','Team_9','Frontend','Staff'),
('Satyajit Das','Team_9','QA','Junior'),
('Rohit Kulshrestha','Team_9','Backend','Mid'),
('Megha Arora','Team_9','Frontend','Senior'),

('Srinidhi Rao','Team_10','QA','Staff'),
('Abhijeet Patil','Team_10','Backend','Junior'),
('Tanushree Ghosh','Team_10','Frontend','Mid'),
('Nikhil Mahajan','Team_10','QA','Senior'),
('Pranav Desai','Team_10','Backend','Staff'),

('Yuvraj Singh','Team_1','Frontend','Junior'),
('Pallavi Arvind','Team_1','QA','Mid'),
('Shubham Verma','Team_1','Backend','Senior'),
('Richa Khanna','Team_1','Frontend','Staff'),
('Kunal Sethi','Team_1','QA','Junior'),

('Harishankar P','Team_2','Backend','Mid'),
('Simran Oberoi','Team_2','Frontend','Senior'),
('Mohit Chandel','Team_2','QA','Staff'),
('Sandeepa M','Team_2','Backend','Junior'),
('Aastha Goel','Team_2','Frontend','Mid'),

('Saurav Nayak','Team_3','QA','Senior'),
('Ritika Joshi','Team_3','Backend','Staff'),
('Shantanu Kulkarni','Team_3','Frontend','Junior'),
('Pratik Shah','Team_3','QA','Mid'),
('Adwaith Krishnan','Team_3','Backend','Senior'),

('Vinod Kumar','Team_4','Frontend','Staff'),
('Nisha Menon','Team_4','QA','Junior'),
('Aman Saxena','Team_4','Backend','Mid'),
('Sneha Rane','Team_4','Frontend','Senior'),
('Raghav Tiwari','Team_4','QA','Staff'),

('Siddharth B','Team_5','Backend','Junior'),
('Tanvi Shah','Team_5','Frontend','Mid'),
('Arif Khan','Team_5','QA','Senior'),
('Nilesh K','Team_5','Backend','Staff'),
('Kritika Anand','Team_5','Frontend','Junior'),

('Rupesh More','Team_6','QA','Mid'),
('Aishani Roy','Team_6','Backend','Senior'),
('Anmol Suri','Team_6','Frontend','Staff'),
('Gaurav Nair','Team_6','QA','Junior'),
('Shilpa Reddy','Team_6','Backend','Mid'),

('Tejashree Patil','Team_7','Frontend','Senior'),
('Ashwin R','Team_7','QA','Staff'),
('Manav Goyal','Team_7','Backend','Junior'),
('Pooja Bhat','Team_7','Frontend','Mid'),
('Ritvik Malhotra','Team_7','QA','Senior'),

('Karthik I','Team_8','Backend','Staff'),
('Sonia Narang','Team_8','Frontend','Junior'),
('Rahil Kapoor','Team_8','QA','Mid'),
('Nandita Kulkarni','Team_8','Backend','Senior'),
('Arjun Pillai','Team_8','Frontend','Staff'),

('Dinesh Chandra','Team_9','QA','Junior'),
('Swati Kulshreshtha','Team_9','Backend','Mid'),
('Ayaan Farooq','Team_9','Frontend','Senior'),
('Ramesh G','Team_9','QA','Staff'),
('Ishika Mathur','Team_9','Backend','Junior'),

('Prithvi Shetty','Team_10','Frontend','Mid'),
('Aparna Iyer','Team_10','QA','Senior'),
('Lokesh Verma','Team_10','Backend','Staff'),
('Mounika R','Team_10','Frontend','Junior'),
('Sameer Purohit','Team_10','QA','Mid'),

('Rajat Mishra','Team_1','Backend','Junior'),
('Aishwarya Sinha','Team_1','Frontend','Mid'),
('Kunal Oberoi','Team_1','QA','Senior'),
('Samar Gupta','Team_1','Backend','Staff'),
('Neha Kakkar','Team_1','Frontend','Junior'),

('Vishal Arora','Team_2','Backend','Mid'),
('Pallavi Mehra','Team_2','QA','Senior'),
('Rohit Talwar','Team_2','Frontend','Staff'),
('Sanjana Roy','Team_2','Backend','Junior'),
('Amit Sehgal','Team_2','QA','Mid'),

('Nikhil Batra','Team_3','Backend','Senior'),
('Riya Khurana','Team_3','Frontend','Staff'),
('Saurav Dey','Team_3','QA','Junior'),
('Karan Mathur','Team_3','Backend','Mid'),
('Ishita Kapoor','Team_3','Frontend','Senior'),

('Pradeep Shetty','Team_4','QA','Staff'),
('Ananya Pillai','Team_4','Backend','Junior'),
('Shashwat Jain','Team_4','Frontend','Mid'),
('Tanya Sengupta','Team_4','QA','Senior'),
('Rohit Kulkarni','Team_4','Backend','Staff'),

('Abhinav Raut','Team_5','Frontend','Junior'),
('Kirti Malhotra','Team_5','QA','Mid'),
('Siddhesh Patil','Team_5','Backend','Senior'),
('Aarohi Shah','Team_5','Frontend','Staff'),
('Naveen Tyagi','Team_5','QA','Junior'),

('Sreenath R','Team_6','Backend','Mid'),
('Kavitha N','Team_6','Frontend','Senior'),
('Harshit Bajaj','Team_6','QA','Staff'),
('Vikram Soni','Team_6','Backend','Junior'),
('Manasi Deshpande','Team_6','Frontend','Mid'),

('Adil Khan','Team_7','QA','Senior'),
('Poonam Kulkarni','Team_7','Backend','Staff'),
('Raghav Singhal','Team_7','Frontend','Junior'),
('Shruti Bansal','Team_7','QA','Mid'),
('Anuj Saxena','Team_7','Backend','Senior'),

('Shivani Joshi','Team_8','Frontend','Staff'),
('Suresh Iyer','Team_8','QA','Junior'),
('Rohan Mallick','Team_8','Backend','Mid'),
('Tanmay Kulshreshtha','Team_8','Frontend','Senior'),
('Mansi Mehta','Team_8','QA','Staff'),

('Abdul Mateen','Team_9','Backend','Junior'),
('Priti Arvind','Team_9','Frontend','Mid'),
('Zeeshan Ali','Team_9','QA','Senior'),
('Nitin Pawaskar','Team_9','Backend','Staff'),
('Shreya N','Team_9','Frontend','Junior'),

('Karthik Suresh','Team_10','QA','Mid'),
('Ankush Goyal','Team_10','Backend','Senior'),
('Mehul Jain','Team_10','Frontend','Staff'),
('Sakshi Chopra','Team_10','QA','Junior'),
('Ritesh Pandit','Team_10','Backend','Mid'),

('Varun Lamba','Team_1','Frontend','Senior'),
('Snehal Parikh','Team_1','QA','Staff'),
('Yogesh Kuldeep','Team_1','Backend','Junior'),
('Nandita Roy','Team_1','Frontend','Mid'),
('Ashish Tandon','Team_1','QA','Senior'),

('Deepika Menon','Team_2','Backend','Staff'),
('Kushagra Agrawal','Team_2','Frontend','Junior'),
('Rupali Gokhale','Team_2','QA','Mid'),
('Aman Verma','Team_2','Backend','Senior'),
('Sonal Jain','Team_2','Frontend','Staff'),

('Arijit Bose','Team_3','QA','Junior'),
('Puja Chakraborty','Team_3','Backend','Mid'),
('Sourav Pal','Team_3','Frontend','Senior'),
('Debopriyo Sen','Team_3','QA','Staff'),
('Ankit Dalmia','Team_3','Backend','Junior'),

('Akshay Raut','Team_4','Backend','Junior'),
('Pallavi Kulkarni','Team_4','Frontend','Mid'),
('Saurabh Khedekar','Team_4','QA','Senior'),
('Renu Mishra','Team_4','Backend','Staff'),
('Nilesh Patwardhan','Team_4','Frontend','Junior'),

('Ankit Chauhan','Team_5','Backend','Mid'),
('Ritika Sood','Team_5','QA','Senior'),
('Vandana Tripathi','Team_5','Frontend','Staff'),
('Raghav Joshi','Team_5','Backend','Junior'),
('Meenal Shah','Team_5','QA','Mid'),

('Sanjay Kuldeep','Team_6','Backend','Senior'),
('Aarti Menon','Team_6','Frontend','Staff'),
('Rohit Khatri','Team_6','QA','Junior'),
('Kiran Patil','Team_6','Backend','Mid'),
('Tanmay Shelar','Team_6','Frontend','Senior'),

('Prerna Goyal','Team_7','QA','Staff'),
('Amol Deshmukh','Team_7','Backend','Junior'),
('Sneha Kulshreshtha','Team_7','Frontend','Mid'),
('Nikhil Anand','Team_7','QA','Senior'),
('Gautam Bhargava','Team_7','Backend','Staff'),

('Usha Rani','Team_8','Frontend','Junior'),
('Akhilesh Yadav','Team_8','QA','Mid'),
('Srinath Iyer','Team_8','Backend','Senior'),
('Kavita Chandra','Team_8','Frontend','Staff'),
('Manoj Lal','Team_8','QA','Junior'),

('Rupesh Thakur','Team_9','Backend','Mid'),
('Nivedita Sen','Team_9','Frontend','Senior'),
('Salman Farooq','Team_9','QA','Staff'),
('Vikas B','Team_9','Backend','Junior'),
('Charu Aggarwal','Team_9','Frontend','Mid'),

('Ramesh Pawar','Team_10','QA','Senior'),
('Apoorva Kulkarni','Team_10','Backend','Staff'),
('Shantanu Ghosh','Team_10','Frontend','Junior'),
('Nitin Malviya','Team_10','QA','Mid'),
('Saurav Kapur','Team_10','Backend','Senior'),

('Ishwar Naik','Team_1','Frontend','Staff'),
('Ruchi Bansal','Team_1','QA','Junior'),
('Adarsh Singh','Team_1','Backend','Mid'),
('Megha Suri','Team_1','Frontend','Senior'),
('Arvind Saxena','Team_1','QA','Staff'),

('Kunal Prasad','Team_2','Backend','Junior'),
('Neetu Arora','Team_2','Frontend','Mid'),
('Rohail Ahmed','Team_2','QA','Senior'),
('Pankaj Rana','Team_2','Backend','Staff'),
('Swati Kulshrestha','Team_2','Frontend','Junior'),

('Anurag Dubey','Team_3','QA','Mid'),
('Ritika Paul','Team_3','Backend','Senior'),
('Sayan Banerjee','Team_3','Frontend','Staff'),
('Tushar Meena','Team_3','QA','Junior'),
('Naveen Joshi','Team_3','Backend','Mid'),

('Prakash Kulkarni','Team_4','Frontend','Senior'),
('Sharmila Nair','Team_4','QA','Staff'),
('Dinesh Bhandari','Team_4','Backend','Junior'),
('Aastha Mishra','Team_4','Frontend','Mid'),
('Ravindra Jadhav','Team_4','QA','Senior'),

('Hemant Choudhary','Team_5','Backend','Staff'),
('Mansi Agarwal','Team_5','Frontend','Junior'),
('Faizan Khan','Team_5','QA','Mid'),
('Satyajeet Patil','Team_5','Backend','Senior'),
('Rupal Doshi','Team_5','Frontend','Staff'),

('Nagaraj H','Team_6','QA','Junior'),
('Shraddha Kulkarni','Team_6','Backend','Mid'),
('Prithviraj Singh','Team_6','Frontend','Senior'),
('Anjali Verma','Team_6','QA','Staff'),
('Vivek Malhotra','Team_6','Backend','Junior'),

('Mahima Arora','Team_7','Frontend','Mid'),
('Deepesh Tiwari','Team_7','QA','Senior'),
('Sandeep Kulkarni','Team_7','Backend','Staff'),
('Riya Khanna','Team_7','Frontend','Junior'),
('Soham Kulkarni','Team_7','QA','Mid'),

('Uday Pratap','Team_8','Backend','Senior'),
('Ira Mallick','Team_8','Frontend','Staff'),
('Rakesh Naidu','Team_8','QA','Junior'),
('Tanvi Deshpande','Team_8','Backend','Mid'),
('Aman Kohli','Team_8','Frontend','Senior'),

('Laxmi Devi','Team_9','QA','Staff'),
('Yash Mehra','Team_9','Backend','Junior'),
('Parul Saxena','Team_9','Frontend','Mid'),
('Sameer Siddiqui','Team_9','QA','Senior'),
('Ketan Rane','Team_9','Backend','Staff'),

('Shalini Goel','Team_10','Frontend','Junior'),
('Nikhil Chawla','Team_10','QA','Mid'),
('Arun Prakash','Team_10','Backend','Senior'),
('Sonam Khandelwal','Team_10','Frontend','Staff'),
('Rizwan Siddique','Team_10','QA','Junior'),

('Bharat Joshi','Team_1','Backend','Mid'),
('Kriti Malhotra','Team_1','Frontend','Senior'),
('Ashok Pillai','Team_1','QA','Staff'),
('Devika Iyer','Team_1','Backend','Junior'),
('Sumeet Verma','Team_1','Frontend','Mid'),

('Poonam Rawat','Team_2','QA','Senior'),
('Alok Srivastava','Team_2','Backend','Staff'),
('Neha Dutta','Team_2','Frontend','Junior'),
('Rahil Mirza','Team_2','QA','Mid'),
('Naveen Hegde','Team_2','Backend','Senior'),

('Sushant N','Team_3','Frontend','Staff'),
('Anita Fernandes','Team_3','QA','Junior'),
('Keshav Tandon','Team_3','Backend','Mid'),
('Moumita Roy','Team_3','Frontend','Senior'),
('Ranjan Mishra','Team_3','QA','Staff'),

('Govind Soni','Team_4','Backend','Junior'),
('Ishika Mathur','Team_4','Frontend','Mid'),
('Zubair Khan','Team_4','QA','Senior'),
('Rohini G','Team_4','Backend','Staff'),
('Manav Batra','Team_4','Frontend','Junior'),

('Ashwin Shetty','Team_5','Backend','Mid'),
('Nandita R','Team_5','QA','Senior'),
('Prateek Lodha','Team_5','Frontend','Staff'),
('Kunal Yadav','Team_5','Backend','Junior'),
('Saumya Nigam','Team_5','QA','Mid'),

('Shreyas Kulkarni','Team_6','Backend','Senior'),
('Ankita Phadke','Team_6','Frontend','Staff'),
('Naveed Pasha','Team_6','QA','Junior'),
('Ritesh Goyal','Team_6','Backend','Mid'),
('Charan Reddy','Team_6','Frontend','Senior'),

('Rupali Sawant','Team_7','QA','Staff'),
('Siddharth Negi','Team_7','Backend','Junior'),
('Mihika Jain','Team_7','Frontend','Mid'),
('Arbaz Khan','Team_7','QA','Senior'),
('Pranita Kulkarni','Team_7','Backend','Staff'),

('Anup Singh','Team_8','Frontend','Junior'),
('Shweta B','Team_8','QA','Mid'),
('Karthikeyan M','Team_8','Backend','Senior'),
('Ritu Chawla','Team_8','Frontend','Staff'),
('Maheshwari S','Team_8','QA','Junior'),

('Ravneet Singh','Team_1','Backend','Junior'),
('Ishita Grover','Team_1','Frontend','Mid'),
('Saurabh Jain','Team_1','QA','Senior'),
('Naman Arora','Team_1','Backend','Staff'),
('Tanya Mehta','Team_1','Frontend','Junior'),

('Harsh Vyas','Team_2','Backend','Mid'),
('Pallavi S','Team_2','QA','Senior'),
('Rohini Deshpande','Team_2','Frontend','Staff'),
('Yogendra Pal','Team_2','Backend','Junior'),
('Ankita Soni','Team_2','QA','Mid'),

('Ritwik Ghosh','Team_3','Backend','Senior'),
('Anushree Patil','Team_3','Frontend','Staff'),
('Suman Dutta','Team_3','QA','Junior'),
('Arnav Bhatt','Team_3','Backend','Mid'),
('Pooja Chatterjee','Team_3','Frontend','Senior'),

('Karthik Ramanan','Team_4','QA','Staff'),
('Shubham Kulkarni','Team_4','Backend','Junior'),
('Riya Srivastava','Team_4','Frontend','Mid'),
('Anirban Paul','Team_4','QA','Senior'),
('Girish B','Team_4','Backend','Staff'),

('Dev Patel','Team_5','Frontend','Junior'),
('Simran Sethi','Team_5','QA','Mid'),
('Raghav Mittal','Team_5','Backend','Senior'),
('Ananya Shah','Team_5','Frontend','Staff'),
('Prakash Verma','Team_5','QA','Junior'),

('Siddharth Nair','Team_6','Backend','Mid'),
('Kavitha R','Team_6','Frontend','Senior'),
('Mohammed Irfan','Team_6','QA','Staff'),
('Akhil S','Team_6','Backend','Junior'),
('Neelima K','Team_6','Frontend','Mid'),

('Suyash Pandey','Team_7','QA','Senior'),
('Monika Arvind','Team_7','Backend','Staff'),
('Pranay Kuldeep','Team_7','Frontend','Junior'),
('Ritu Sinha','Team_7','QA','Mid'),
('Vikrant Pawar','Team_7','Backend','Senior'),

('Sonal Agrawal','Team_8','Frontend','Staff'),
('Aditya Menon','Team_8','QA','Junior'),
('Pradeep K','Team_8','Backend','Mid'),
('Sanchita Roy','Team_8','Frontend','Senior'),
('Manjunath H','Team_8','QA','Staff'),

('Zoya Khan','Team_9','Backend','Junior'),
('Nitin Choudhary','Team_9','Frontend','Mid'),
('Adeel Ahmed','Team_9','QA','Senior'),
('Rakesh Solanki','Team_9','Backend','Staff'),
('Purnima Joshi','Team_9','Frontend','Junior'),

('Ashwin Kulkarni','Team_10','QA','Mid'),
('Saket Tiwari','Team_10','Backend','Senior'),
('Rupal Mehra','Team_10','Frontend','Staff'),
('Kunal Vohra','Team_10','QA','Junior'),
('Deepak Saini','Team_10','Backend','Mid'),

('Varsha Iyer','Team_1','Frontend','Senior'),
('Nilesh Patil','Team_1','QA','Staff'),
('Arpit Goyal','Team_1','Backend','Junior'),
('Srishti Malhotra','Team_1','Frontend','Mid'),
('Rahul Nambiar','Team_1','QA','Senior'),

('Bhavana Reddy','Team_2','Backend','Staff'),
('Tushar Saxena','Team_2','Frontend','Junior'),
('Snehal K','Team_2','QA','Mid'),
('Abhishek Tomar','Team_2','Backend','Senior'),
('Ila Banerjee','Team_2','Frontend','Staff'),

('Sohail Ansari','Team_3','QA','Junior'),
('Ritika Kulkarni','Team_3','Backend','Mid'),
('Anup Ghosh','Team_3','Frontend','Senior'),
('Shreyan Bose','Team_3','QA','Staff'),
('Kunal Tripathi','Team_3','Backend','Junior');	


SELECT COUNT(*) AS total_employees FROM employees;

select * from employees;

ALTER TABLE employees
DROP COLUMN created_at;



